import turtle
def Cartesian_Coordinate_System():
    t=turtle.Turtle()
    t.speed(0)
    for i in range(0,401,20):
        t.pencolor('lightgrey')
        t.penup()
        t.setpos(-200+i,-200)
        if i==0:
            t.left(90)
        t.pendown()
        t.forward(400)
        t.backward(400)
    for i in range(0,401,20):
        t.pencolor('lightgrey')
        t.penup()
        t.setpos(-200,-200+i)
        if i==0:
            t.right(90)
        t.pendown()
        t.forward(400)
        t.backward(400)
    t.penup()
    t.home()
    t.pendown()
    t.pencolor('black')
    t.backward(200)
    t.forward(400)
    t.backward(200)
    t.left(90)
    t.forward(200)
    t.backward(400)
    t.penup()
    t.setpos(5,5)
    t.pendown()
    t.write(0)
    t.penup()
    t.setpos(190,5)
    t.pendown()
    t.write("x")
    t.penup()
    t.setpos(5,190)
    t.pendown()
    t.write("y")
    t.ht()